version: '3'
services:
  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: psu
      POSTGRES_USER: psu
      POSTGRES_DB: ukpostal
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./csv:/var/lib/postgresql/csv
    ports:
      - 5432:5432
