version: '3.1'

services:
  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: psu
      POSTGRES_USER: psu
      POSTGRES_DB: ukpostal
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./csv:/var/lib/postgresql/csv
    ports:
      - 5432:5432

  app:
    image: openjdk:17-jdk
    volumes:
      - .:/app
    working_dir: /app
    command: ./mvnw spring-boot:run
    depends_on:
      - db
    links:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ukpostal
      SPRING_DATASOURCE_USERNAME: psu
      SPRING_DATASOURCE_PASSWORD: psu

  test:
    image: openjdk:17-jdk
    volumes:
      - .:/app
    working_dir: /app
    command: ./mvnw test
    depends_on:
      - db
    links:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ukpostal
      SPRING_DATASOURCE_USERNAME: psu
      SPRING_DATASOURCE_PASSWORD: psu