version: '3.1'

services:
  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: psu
      POSTGRES_USER: psu
      POSTGRES_DB: ukpostal
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./csv:/csv
    ports:
      - 5432:5432
